security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        istore\SecurityBundle\Entity\User: plaintext
        #istore\SecurityBundle\Entity\User:
        #    algorithm:        sha1
        #    encode_as_base64: false
        #    iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: istoreSecurityBundle:User }
            
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        admin_area:
            pattern:    ^/admin
            http_basic: ~
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                always_use_default_target_path: true
                default_target_path: ^/category

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
