#security:
#    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
#        istore\SecurityBundle\Entity\User: plaintext
        #istore\SecurityBundle\Entity\User:
        #    algorithm:        sha1
        #    encode_as_base64: false
        #    iterations:       1

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

#    providers:
#        administrators:
#            entity: { class: istoreSecurityBundle:User }
            
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

#    firewalls:
        #admin_area:
        #    pattern:    ^/admin
        #    http_basic: ~
        #dev:
        #    pattern:  ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        #login:
        #    pattern:  ^/login$
        #    security: false

#        secured_area:
#            pattern:    ^/
#            anonymous: ~
#            form_login:
#                login_path:  /login
#                check_path:  /login_check
#                always_use_default_target_path: true
#                default_target_path: ^/
                #failure_path: /login_failure

#    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #, requires_channel: https }
        
        
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            context: primary_auth
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/ , role: ROLE_USER }
        - { path: ^/sale$ , role: ROLE_USER }
        - { path: ^/customer$ , role: ROLE_USER }
        - { path: ^/item$ , role: ROLE_ADMIN }
        - { path: ^/bulk$ , role: ROLE_ADMIN }
        - { path: ^/model$ , role: ROLE_ADMIN }
        - { path: ^/category$ , role: ROLE_ADMIN }
        - { path: ^/supplier$ , role: ROLE_ADMIN }
        - { path: ^/warranty$ , role: ROLE_ADMIN }
        - { path: ^/report$ , role: ROLE_ADMIN }