istoregomlaphone_default:
    path:  /
    defaults: { _controller: istoregomlaphoneBundle:Default:index }
    requirements:
        _method: GET
        
istoregomlaphone_category_index:
    pattern:  /category
    defaults: { _controller: istoregomlaphoneBundle:Category:index }

istoregomlaphone_category_add:
    pattern:  /category/add
    defaults: { _controller: istoregomlaphoneBundle:Category:add }

istoregomlaphone_category_edit:
    pattern:  /category/edit/{id}
    defaults: { _controller: istoregomlaphoneBundle:Category:edit }

istoregomlaphone_category_delete:
    pattern:  /category/delete/{id}
    defaults: { _controller: istoregomlaphoneBundle:Category:delete }

istoregomlaphone_category_find:
    pattern:  /category/find
    defaults: { _controller: istoregomlaphoneBundle:Category:find }

istoregomlaphone_category_validate:
    pattern:  /category/validate
    defaults: { _controller: istoregomlaphoneBundle:Category:validate }

istoregomlaphone_color_index:
    pattern:  /color
    defaults: { _controller: istoregomlaphoneBundle:Color:index }

istoregomlaphone_color_add:
    pattern:  /color/add
    defaults: { _controller: istoregomlaphoneBundle:Color:add }

istoregomlaphone_color_edit:
    pattern:  /color/edit/{id}
    defaults: { _controller: istoregomlaphoneBundle:Color:edit }

istoregomlaphone_color_delete:
    pattern:  /color/delete/{id}
    defaults: { _controller: istoregomlaphoneBundle:Color:delete }

istoregomlaphone_color_find:
    pattern:  /color/find
    defaults: { _controller: istoregomlaphoneBundle:Color:find }

istoregomlaphone_color_validate:
    pattern:  /color/validate
    defaults: { _controller: istoregomlaphoneBundle:Color:validate }

istoregomlaphone_brand_index:
    pattern:  /brand
    defaults: { _controller: istoregomlaphoneBundle:Brand:index }

istoregomlaphone_brand_add:
    pattern:  /brand/add
    defaults: { _controller: istoregomlaphoneBundle:Brand:add }

istoregomlaphone_brand_edit:
    pattern:  /brand/edit/{id}
    defaults: { _controller: istoregomlaphoneBundle:Brand:edit }

istoregomlaphone_brand_delete:
    pattern:  /brand/delete/{id}
    defaults: { _controller: istoregomlaphoneBundle:Brand:delete }

istoregomlaphone_brand_find:
    pattern:  /brand/find
    defaults: { _controller: istoregomlaphoneBundle:Brand:find }

istoregomlaphone_brand_validate:
    pattern:  /brand/validate
    defaults: { _controller: istoregomlaphoneBundle:Brand:validate }

istoregomlaphone_model_index:
    pattern:  /model
    defaults: { _controller: istoregomlaphoneBundle:Model:index }

istoregomlaphone_model_add:
    pattern:  /model/add
    defaults: { _controller: istoregomlaphoneBundle:Model:add }

istoregomlaphone_model_edit:
    pattern:  /model/edit/{id}
    defaults: { _controller: istoregomlaphoneBundle:Model:edit }

istoregomlaphone_model_delete:
    pattern:  /model/delete/{id}
    defaults: { _controller: istoregomlaphoneBundle:Model:delete }

istoregomlaphone_model_find:
    pattern:  /model/find
    defaults: { _controller: istoregomlaphoneBundle:Model:find }

istoregomlaphone_model_validate:
    pattern:  /model/validate
    defaults: { _controller: istoregomlaphoneBundle:Model:validate }

istoregomlaphone_supplier_index:
    pattern:  /supplier
    defaults: { _controller: istoregomlaphoneBundle:Supplier:index }
    
istoregomlaphone_supplier_add:
    pattern:  /supplier/add
    defaults: { _controller: istoregomlaphoneBundle:Supplier:add }

istoregomlaphone_supplier_transaction:
    pattern:  /supplier/{id}
    defaults: { _controller: istoregomlaphoneBundle:Transaction:index }

istoregomlaphone_supplier_edit:
    pattern:  /supplier/edit/{id}
    defaults: { _controller: istoregomlaphoneBundle:Supplier:edit }

istoregomlaphone_supplier_delete:
    pattern:  /supplier/delete/{id}
    defaults: { _controller: istoregomlaphoneBundle:Supplier:delete }

istoregomlaphone_bulk_index:
    pattern:  /bulk
    defaults: { _controller: istoregomlaphoneBundle:Bulk:index }

istoregomlaphone_bulk_view:
    pattern:  /bulk/view/{id}
    defaults: { _controller: istoregomlaphoneBundle:Bulk:view }

istoregomlaphone_bulk_add:
    pattern:  /bulk/add
    defaults: { _controller: istoregomlaphoneBundle:Bulk:add }

istoregomlaphone_bulk_edit:
    pattern:  /bulk/edit/{id}
    defaults: { _controller: istoregomlaphoneBundle:Bulk:edit }

istoregomlaphone_bulk_delete:
    pattern:  /bulk/delete/{id}
    defaults: { _controller: istoregomlaphoneBundle:Bulk:delete }

istoregomlaphone_bulk_wizard:
    pattern:  /bulk/wizard
    defaults: { _controller: istoregomlaphoneBundle:Bulk:wizard }

istoregomlaphone_item_index:
    pattern:  /item
    defaults: { _controller: istoregomlaphoneBundle:Item:index }

istoregomlaphone_item_add:
    pattern:  /item/add
    defaults: { _controller: istoregomlaphoneBundle:Item:add }

istoregomlaphone_item_edit:
    pattern:  /item/edit
    defaults: { _controller: istoregomlaphoneBundle:Item:edit }

istoregomlaphone_item_validate:
    pattern:  /item/validate
    defaults: { _controller: istoregomlaphoneBundle:Item:validate }

istoregomlaphone_item_delete:
    pattern:  /item/delete/{id}
    defaults: { _controller: istoregomlaphoneBundle:Item:delete }

istoregomlaphone_item_find:
    pattern:  /item/find
    defaults: { _controller: istoregomlaphoneBundle:Item:find }

istoregomlaphone_item_get:
    pattern:  /item/get
    defaults: { _controller: istoregomlaphoneBundle:Item:get }

istoregomlaphone_item_wizard:
    pattern:  /item/wizard/{id}
    defaults: { _controller: istoregomlaphoneBundle:Item:wizard }

istoregomlaphone_sale_index:
    pattern:  /sale
    defaults: { _controller: istoregomlaphoneBundle:Sale:index }

istoregomlaphone_sale_postpaid:
    pattern:  /sale/postpaid
    defaults: { _controller: istoregomlaphoneBundle:Sale:postpaid }

istoregomlaphone_sale_postpaid_view:
    pattern:  /sale/postpaid/view
    defaults: { _controller: istoregomlaphoneBundle:Sale:viewPayments }

istoregomlaphone_sale_postpaid_refund:
    pattern:  /sale/postpaid/refund/{id}
    defaults: { _controller: istoregomlaphoneBundle:Sale:refundPayment }

istoregomlaphone_sale_postpaid_view_add:
    pattern:  /sale/postpaid/add
    defaults: { _controller: istoregomlaphoneBundle:Sale:viewAddPayment }

istoregomlaphone_sale_postpaid_add:
    pattern:  /sale/postpaid/add/{id}
    defaults: { _controller: istoregomlaphoneBundle:Sale:addPayment }

istoregomlaphone_sale_prepaid:
    pattern:  /sale/prepaid
    defaults: { _controller: istoregomlaphoneBundle:Sale:prepaid }

istoregomlaphone_sale_discount:
    pattern:  /sale/discount
    defaults: { _controller: istoregomlaphoneBundle:Sale:discount }

istoregomlaphone_sale_confirm_discount:
    pattern:  /sale/discount/{id}
    defaults: { _controller: istoregomlaphoneBundle:Sale:confirmDiscount }

istoregomlaphone_sale_add:
    pattern:  /sale/add
    defaults: { _controller: istoregomlaphoneBundle:Sale:add }

istoregomlaphone_sale_edit:
    pattern:  /sale/edit/{id}
    defaults: { _controller: istoregomlaphoneBundle:Sale:edit }

istoregomlaphone_sale_bill:
    pattern:  /sale/bill/{id}
    defaults: { _controller: istoregomlaphoneBundle:Sale:bill }
    
istoregomlaphone_sale_bill_first:
    pattern:  /sale/bill/{id}/{first}
    defaults: { _controller: istoregomlaphoneBundle:Sale:bill }

istoregomlaphone_sale_refund:
    pattern:  /sale/refund/{id}
    defaults: { _controller: istoregomlaphoneBundle:Sale:refund }

istoregomlaphone_customer_index:
    pattern:  /customer
    defaults: { _controller: istoregomlaphoneBundle:Customer:index }

istoregomlaphone_customer_find:
    pattern:  /customer/find
    defaults: { _controller: istoregomlaphoneBundle:Customer:find }

istoregomlaphone_customer_query:
    pattern:  /customer/query
    defaults: { _controller: istoregomlaphoneBundle:Customer:query }

istoregomlaphone_customer_add:
    pattern:  /customer/add
    defaults: { _controller: istoregomlaphoneBundle:Customer:add }

istoregomlaphone_customer_validate:
    pattern:  /customer/validate
    defaults: { _controller: istoregomlaphoneBundle:Customer:validate }

istoregomlaphone_customer_sale:
    pattern:  /customer/{id}
    defaults: { _controller: istoregomlaphoneBundle:Default:index }

istoregomlaphone_customer_edit:
    pattern:  /customer/edit/{id}
    defaults: { _controller: istoregomlaphoneBundle:Customer:edit }

istoregomlaphone_customer_prepaid:
    pattern:  /customer/prepaid/{id}
    defaults: { _controller: istoregomlaphoneBundle:Customer:prepaid }

istoregomlaphone_customer_postpaid:
    pattern:  /customer/postpaid/{id}
    defaults: { _controller: istoregomlaphoneBundle:Customer:postpaid }

istoregomlaphone_warranty_index:
    pattern:  /warranty
    defaults: { _controller: istoregomlaphoneBundle:Warranty:index }

istoregomlaphone_warranty_add:
    pattern:  /warranty/add
    defaults: { _controller: istoregomlaphoneBundle:Warranty:add }

istoregomlaphone_warranty_edit:
    pattern:  /warranty/edit/{id}
    defaults: { _controller: istoregomlaphoneBundle:Warranty:edit }

istoregomlaphone_warranty_delete:
    pattern:  /warranty/delete/{id}
    defaults: { _controller: istoregomlaphoneBundle:Warranty:delete }

istoregomlaphone_warranty_find:
    pattern:  /warranty/find
    defaults: { _controller: istoregomlaphoneBundle:Warranty:find }

istoregomlaphone_warranty_validate:
    pattern:  /warranty/validate
    defaults: { _controller: istoregomlaphoneBundle:Warranty:validate }

istoregomlaphone_report_index:
    pattern:  /report
    defaults: { _controller: istoregomlaphoneBundle:Report:index }

istoregomlaphone_report_view:
    pattern:  /report/view
    defaults: { _controller: istoregomlaphoneBundle:Report:view }

istoregomlaphone_report_export:
    pattern:  /report/export
    defaults: { _controller: istoregomlaphoneBundle:Report:export }

istoregomlaphone_report_print:
    pattern:  /report/print
    defaults: { _controller: istoregomlaphoneBundle:Report:print }

istoregomlaphone_user_index:
    pattern:  /user
    defaults: { _controller: istoregomlaphoneBundle:User:index }

istoregomlaphone_user_add:
    pattern:  /user/add
    defaults: { _controller: FOSUserBundle:Registration:register }

istoregomlaphone_user_edit:
    pattern:  /user/edit/{id}
    defaults: { _controller: FOSUserBundle:Registration:register }

istoregomlaphone_user_delete:
    pattern:  /user/delete/{id}
    defaults: { _controller: istoregomlaphoneBundle:User:delete }

istoregomlaphone_user_change_password:
    pattern:  /user/changepassword/{id}
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }

istoregomlaphone_search:
    pattern:  /search
    defaults: { _controller: istoregomlaphoneBundle:Search:index }

istoregomlaphone_store_index:
    pattern:  /store
    defaults: { _controller: istoregomlaphoneBundle:Store:index }

istoregomlaphone_store_add:
    pattern:  /store/add
    defaults: { _controller: istoregomlaphoneBundle:Store:add }

istoregomlaphone_store_edit:
    pattern:  /store/edit/{id}
    defaults: { _controller: istoregomlaphoneBundle:Store:edit }

istoregomlaphone_store_delete:
    pattern:  /store/delete/{id}
    defaults: { _controller: istoregomlaphoneBundle:Store:delete }

istoregomlaphone_transaction:
    pattern:  /transaction/{id}
    defaults: { _controller: istoregomlaphoneBundle:Transaction:view }

istoregomlaphone_transaction_edit_wizard:
    pattern:  /transaction/wizard/{id}
    defaults: { _controller: istoregomlaphoneBundle:Transaction:wizard }

istoregomlaphone_transaction_edit:
    pattern:  /transaction/edit/{id}
    defaults: { _controller: istoregomlaphoneBundle:Transaction:edit }

istoregomlaphone_transaction_payment_view_add:
    pattern:  /payment/add
    defaults: { _controller: istoregomlaphoneBundle:Transaction:viewAddPayment }

istoregomlaphone_transaction_payment_add:
    pattern:  /payment/add/{id}
    defaults: { _controller: istoregomlaphoneBundle:Transaction:addPayment }

istoregomlaphone_transaction_payment_view:
    pattern:  /payment/view
    defaults: { _controller: istoregomlaphoneBundle:Transaction:viewPayments }

istoregomlaphone_transaction_payment_refund:
    pattern:  /payment/refund/{id}
    defaults: { _controller: istoregomlaphoneBundle:Transaction:refundPayment }

istoregomlaphone_stock_index:
    pattern:  /stock
    defaults: { _controller: istoregomlaphoneBundle:Stock:index }

istoregomlaphone_stock_search:
    pattern:  /stock/search
    defaults: { _controller: istoregomlaphoneBundle:Stock:search }
