parameters:
#    istoregomlaphone.example.class: istore\gomlaphoneBundle\Example

services:
#    istoregomlaphone.example:
#        class: %istoregomlaphone.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
